# Generated by Django 3.2.4 on 2021-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article name')),
                ('text', models.TextField(verbose_name='Article text')),
                ('img_url', models.URLField(max_length=250, verbose_name='picture png')),
            ],
        ),
    ]
